### all
POST http://localhost:8080/api/multi/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\2025-12-20-式輿防衛戰\\2025-12-20-式輿防衛戰.mp4",
  "description": "練度展示於結尾\r\n",
  "playlist": "絕區零-高難",
  "hashtags": ["絕區零", "ZenlessZoneZero"]
}