### TikTok Upload Example
POST http://localhost:8080/api/tiktok/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\OBS-VidoeRecord\\2025-11-21 21-40-39.mp4",
  "caption": "2025-11-21-式輿防衛戰\r\n\r\n練度展示於結尾\r\n\r\n#絕區零 #ZenlessZoneZero ",
  "visibility": "PUBLIC"
}
