### 原神
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\OBS-VidoeRecord\\2025-11-21 21-40-39.mp4",
  "title": "2025-11-21-",
  "description": "練度展示於結尾\r\n#原神 #GenshinImpact ",
  "playlist": "原神-高難",
  "visibility": "PUBLIC"
}

### 崩鐵
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\OBS-VidoeRecord\\2025-11-21 21-40-39.mp4",
  "title": "2025-11-21-",
  "description": "練度展示於結尾\r\n#崩壞星穹鐵道 #HonkaiStarRail ",
  "playlist": "崩壞:星穹鐵道-高難",
  "visibility": "PUBLIC"
}

### 絕區零
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\OBS-VidoeRecord\\2025-11-21 21-40-39.mp4",
  "title": "2025-11-21-",
  "description": "練度展示於結尾\r\n#絕區零 #ZenlessZoneZero ",
  "playlist": "絕區零-高難",
  "visibility": "PUBLIC"
}
