### all
POST http://localhost:8080/api/multi/upload/folder
Content-Type: application/json

{
  "folderPath": "F:\\2026-02-02-末日幻影-支配溟茫",
  "description": "練度展示於結尾\r\n",
  "playlist": "崩壞:星穹鐵道-高難",
  "hashtags": ["崩壞星穹鐵道", "HonkaiStarRail", "支配溟茫"]
}
