### Integrated Upload Test
POST http://localhost:8080/api/integrated/upload
Content-Type: application/json

{
    "filePath": "D:\\Download\\OBS-VidoeRecord\\2025-11-25-虛構敘事-程式語法.mp4",
    "title": "2025-11-25-虛構敘事-程式語法",
    "description": "練度展示於結尾",
    "hashtags": ["崩壞星穹鐵道", "HonkaiStarRail"],
    "visibility": "PUBLIC",
    "playlist": "崩壞:星穹鐵道-高難",
    "platforms": ["YOUTUBE", "TIKTOK", "XIAOHONGSHU", "BILIBILI"]
}
### 崩鐵
POST http://localhost:8080/api/integrated/upload
Content-Type: application/json

{
    "filePath": "D:\\Download\\OBS-VidoeRecord\\2025-11-25-虛構敘事-程式語法.mp4",
    "title": "2025-11-25-虛構敘事-程式語法",
    "description": "練度展示於結尾",
    "hashtags": ["崩壞星穹鐵道", "HonkaiStarRail"],
    "visibility": "PUBLIC",
    "playlist": "崩壞:星穹鐵道-高難",
    "platforms": ["YOUTUBE", "TIKTOK", "XIAOHONGSHU", "BILIBILI"]
}
