### 崩壞三
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\OBS-VidoeRecord\\崩壞三-往世樂土11.mkv",
  "title": "崩壞三-往世樂土-11",
  "description": "劇情\r\n#崩壞三 #HonkaiImpact3rd",
  "playlist": "崩壞三",
  "visibility": "PUBLIC",
  "hashtags": ["#崩壞三", "#HonkaiImpact3rd"]
}


### 原神
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\OBS-VidoeRecord\\2025-11-21 21-40-39.mp4",
  "title": "2025-11-21-",
  "description": "練度展示於結尾\r\n#原神 #GenshinImpact ",
  "playlist": "原神-高難",
  "visibility": "PUBLIC",
  "hashtags": ["#原神", "#GenshinImpact"]
}

### 崩鐵
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\OBS-VidoeRecord\\2025-11-21 21-40-39.mp4",
  "title": "2025-11-21-",
  "description": "練度展示於結尾",
  "playlist": "崩壞:星穹鐵道-高難",
  "visibility": "PUBLIC",
  "hashtags": ["#崩壞星穹鐵道", "#HonkaiStarRail"]
}

### 絕區零
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\2.4-將臨未抵的深淵\\2.4-將臨未抵的深淵-1.mp4",
  "title": "2.4-將臨未抵的深淵",
  "description": "劇情",
  "playlist": "絕區零",
  "visibility": "PUBLIC",
  "hashtags": ["#絕區零", "#ZenlessZoneZero", "#將臨未抵的深淵"]
}
