### FB
POST http://localhost:8080/api/post/facebook
Content-Type: application/json

{
    "videoUrl": "https://youtu.be/C5fpUENsvIM",
    "title": "2025-12-07-式輿防衛戰",
    "description": "練度展示於結尾",
    "hashtags": ["絕區零", "ZenlessZoneZero"]
}

### threads
POST http://localhost:8080/api/post/threads
Content-Type: application/json

{
    "videoUrl": "https://youtu.be/C5fpUENsvIM",
    "title": "2025-12-07-式輿防衛戰",
    "description": "練度展示於結尾",
    "topic": "絕區零"
}

### x
POST http://localhost:8080/api/post/x
Content-Type: application/json

{
    "videoUrl": "https://youtu.be/C5fpUENsvIM",
    "title": "2025-12-07-式輿防衛戰",
    "description": "練度展示於結尾",
    "hashtags": ["絕區零", "ZenlessZoneZero"]
}

### hoyolab
POST http://localhost:8080/api/post/hoyolab
Content-Type: application/json

{
    "videoUrl": "https://youtu.be/C5fpUENsvIM",
    "title": "2025-12-07-式輿防衛戰",
    "description": "練度展示於結尾",
    "category": "攻略與分析",
    "hashtags": ["絕區零", "ZenlessZoneZero"]
}