### all
POST http://localhost:8080/api/multi/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\未上傳\\赤龍之章\\赤龍之章-5.mp4",
  "description": "劇情\r\n",
  "playlist": "原神",
  "hashtags": ["原神", "genshinimpact", "赤龍之章"]
}

### youtube
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\未上傳\\赤龍之章\\赤龍之章-4.mp4",
  "description": "劇情\r\n",
  "playlist": "原神",
  "visibility": "PUBLIC",
  "hashtags": ["原神", "genshinimpact", "赤龍之章"]
}
### bilibili
POST http://localhost:8080/api/bilibili/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\未上傳\\赤龍之章\\赤龍之章-4.mp4",
  "description": "劇情\r\n",
  "visibility": "public",
  "hashtags": ["原神", "genshinimpact", "赤龍之章"]
}
### 小紅書
POST http://localhost:8080/api/xiaohongshu/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\未上傳\\赤龍之章\\赤龍之章-4.mp4",
  "description": "劇情\r\n",
  "visibility": "public",
  "hashtags": ["原神", "genshinimpact", "赤龍之章"]
}

### TikTok ｛
POST http://localhost:8080/api/tiktok/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\未上傳\\赤龍之章\\赤龍之章-4.mp4",
  "description": "劇情\r\n",
  "visibility": "PUBLIC",
  "hashtags": ["原神", "GenshinImpact", "赤龍之章"]
}
