### youtube
POST http://localhost:8080/api/youtube/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\2025-12-07-幻想真境劇詩\\2025-12-07-幻想真境劇詩.mp4",
  "description": "練度展示於結尾\r\n",
  "playlist": "原神",
  "visibility": "PUBLIC",
  "hashtags": ["原神", "genshinimpact", "月之三"]
}
### bilibili
POST http://localhost:8080/api/bilibili/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\2025-12-07-幻想真境劇詩\\2025-12-07-幻想真境劇詩.mp4",
  "description": "練度展示於結尾\r\n",
  "visibility": "public",
  "hashtags": ["原神", "genshinimpact", "月之三"]
}
### 小紅書
POST http://localhost:8080/api/xiaohongshu/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\2025-12-07-幻想真境劇詩\\2025-12-07-幻想真境劇詩.mp4",
  "description": "練度展示於結尾\r\n",
  "visibility": "public",
  "hashtags": ["原神", "genshinimpact", "月之三"]
}

### TikTok ｛
POST http://localhost:8080/api/tiktok/upload
Content-Type: application/json

{
  "filePath": "D:\\Download\\2025-12-07-幻想真境劇詩\\2025-12-07-幻想真境劇詩.mp4",
  "description": "練度展示於結尾\r\n",
  "visibility": "PUBLIC",
  "hashtags": ["原神", "GenshinImpact", "月之三"]
}
