### all
POST http://localhost:8080/api/multi/upload/folder
Content-Type: application/json

{
  "folderPath": "F:\\未上傳\\奔霄頌玉輪-第一幕-在雲間",
  "description": "劇情\r\n",
  "playlist": "原神",
  "hashtags": ["原神", "genshinimpact", "月之四", "奔霄頌玉輪", "在雲間"]
}