### all
POST http://localhost:8080/api/multi/upload/folder
Content-Type: application/json

{
  "folderPath": "F:\\OBS-VideoRecord\\月之四",
  "description": "劇情\r\n",
  "playlist": "原神",
  "hashtags": ["原神", "genshinimpact", "月之四", "如果在冬夜一個旅人", "真實之月"]
}